### ISSUE TITLE
`updater.enable_notification=false` should disable version checking even in `version` command

### ISSUE THREAD

**Issue by RobMeades** [arduino/arduino-cli#1483]
## Bug Report
In #1480 I had a problem with the update notification string from `arduino-cli` containing a unicode character which doesn't map to anything by default when run under a Python [3.8] script on Windows 10, causing Python to raise an exception.  The conclusion to that was that I could either sort my goldarned Python/Windows code-page out or disable the notification with:

```
arduino-cli config set updater.enable_notification false
```
While the former was in progress I did the latter but I didn't actually _check_ that it was working because I had already updated my `arduino-cli` version.

My problem is that the notification remains even when I've apparently disabled it, see below.  What am I doing wrong?

### Current behaviour
Dumping my config, you can see that `updater.enable_notification` is `false`.

```
>arduino-cli config dump
board_manager:
  additional_urls: []
daemon:
  port: "50051"
directories:
  data: C:\Users\rob\AppData\Local\Arduino15
  downloads: C:\Users\rob\AppData\Local\Arduino15\staging
  user: C:\Users\rob\Documents\Arduino
library:
  enable_unsafe_install: false
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
output:
  no_color: false
sketch:
  always_export_binaries: false
updater:
  enable_notification: false
```

...but when I run, for instance, `arduino-cli version` the "update is available" string still pops out:

```
>arduino-cli version
arduino-cli alpha Version: 0.19.1 Commit: 718bbbf2 Date: 2021-09-29T08:28:11Z

A new release of Arduino CLI is available: 0.19.1 → 0.19.2
https://arduino.github.io/arduino-cli/latest/installation/#latest-packages
```

### Expected behaviour
I would expect to see just:

```
>arduino-cli version
arduino-cli alpha Version: 0.19.1 Commit: 718bbbf2 Date: 2021-09-29T08:28:11Z
```
...no "update is available" string

### Environment
- CLI version: see above
- Windows 10Pro 20H2
