### ISSUE TITLE
ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS not able to take multiple URLs

### ISSUE THREAD

**Issue by vergissberlin** [arduino/arduino-cli#1632]
### Current behavior

In a Docker file or even with a `export` I tried to add multiple URLs (As the variable name suggests) like so
`ENV ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS=[https://dl.espressif.com/dl/package_esp32_index.json,https://arduino.esp8266.com/stable/package_esp8266com_index.json]`
But in the end in the yaml file I get this

```yml
board_manager:
  additional_urls: '[https://dl.espressif.com/dl/package_esp32_index.json,https://arduino.esp8266.com/stable/package_esp8266com_index.json]'
```
So, the ENV variable is a string and we are not able to add more than one URL.

### Expected behavior

```yml
board_manager:
  additional_urls: [https://dl.espressif.com/dl/package_esp32_index.json,https://arduino.esp8266.com/stable/package_esp8266com_index.json]
```

or

```yml
board_manager:
  additional_urls:  
    - https://dl.espressif.com/dl/package_esp32_index.json
    - https://arduino.esp8266.com/stable/package_esp8266com_index.json
```

### Environment

- CLI version (output of `arduino-cli version`): `arduino-cli  Version: 0.20.2 Commit: 13783819 Date: 2021-12-09T13:32:05Z`
- OS and platform: linux
