### ISSUE TITLE
Add `programmer` to the sketch profile

### ISSUE THREAD

**Issue by dankeboy36** [arduino/arduino-cli#2487]
### Describe the request

Include `programmer` in the [sketch project file](https://arduino.github.io/arduino-cli/latest/sketch-project-file/) (aka `sketch.yaml`).

Getting the debug information (via `debug --info`) requires the `fqbn` **and** the `programmer`. 

The FQBN and all custom board options are "encoded" in the `fqbn` property of the profile, but there is no way to store the `programmer`. If the `port`, `protocol`, `fqbn`, etc., can have a default, maybe adding a slot for the `programmer` could also make sense.

Assume this profile:

```yaml
profiles:
  nanorp:
    fqbn: arduino:mbed_nano:nanorp2040connect
    programmer: p1
    platforms:
      - platform: arduino:mbed_nano (2.1.0)

default_profile: nanorp
```

Running `arduino-cli debug --info --profile nanorp` would implicitly run `arduino-cli debug --info --fqbn arduino:mbed_nano:nanorp2040connect --programmer p1`.

### Describe the current behavior

There is no way to store the programmer in the sketch profile. This will be a problem in Arduino IDE when people want to opt in and start storing the FQBN + the custom board options in a file and sharing it with others.

### Arduino CLI version

0.35

### Operating system

N/A

### Operating system version

n/a

### Issue checklist

- [X] I searched for previous requests in [the issue tracker](https://github.com/arduino/arduino-cli/issues?q=)
- [X] I verified the feature was still missing when using the [nightly build](https://arduino.github.io/arduino-cli/dev/installation/#nightly-builds)
- [X] My request contains all necessary details
