### ISSUE TITLE
Q: How to use sketchbook/hardware directory instead of ~/.arduino15/packages/

### ISSUE THREAD

**Issue by sej7278** [arduino/arduino-cli#898]
I don't like the way boards manager in the IDE dumps everything into a hidden directory, is there a way to avoid that with arduino-cli?

I tried setting the following in arduino-cli.yaml but it ended up just creating a packages directory where I expected the cores to go:

```
directories:
  data: /home/user/.arduino15
  downloads: /home/user/arduino16/hardware
  user: /home/simon/user/arduino16
```

Is there a way to force the cores to go into the hardware directory inside the user sketchbook instead of ~/.arduino15/packages/arduino/hardware/avr/1.8.3 ?

`arduino-cli core list` seems to list the cores from there, so surely it can install to there too?

Libraries seem to work this way (install/update work fine) but not cores.
